### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adiantek** [confuser/BarAPI#58]
````
[23:25:52 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_7_R4.PacketPlayOutEntityTeleport.<init>(int, int, int, int, byte, byte)
[23:25:52 WARN]:        at java.lang.Class.getConstructor0(Class.java:3082)
[23:25:52 WARN]:        at java.lang.Class.getConstructor(Class.java:1825)
[23:25:52 WARN]:        at me.confuser.barapi.nms.v1_7.getTeleportPacket(v1_7.java:139)
[23:25:52 WARN]:        at me.confuser.barapi.BarAPI.sendDragon(BarAPI.java:439)
[23:25:52 WARN]:        at me.confuser.barapi.BarAPI.setMessage(BarAPI.java:259)
[23:25:52 WARN]:        at org.primesoft.asyncworldedit.progressDisplay.BarAPIIntegrator.setMessage(BarAPIIntegrator.java:106)
[23:25:52 WARN]:        at org.primesoft.asyncworldedit.progressDisplay.ProgressDisplayManager.setMessage(ProgressDisplayManager.java:97)
[23:25:52 WARN]:        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.setBar(BlockPlacer.java:919)
[23:25:52 WARN]:        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.showProgress(BlockPlacer.java:961)
[23:25:52 WARN]:        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:305)
[23:25:52 WARN]:        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.access$000(BlockPlacer.java:69)
[23:25:52 WARN]:        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer$1.run(BlockPlacer.java:206)
[23:25:52 WARN]:        at org.primesoft.asyncworldedit.blockPlacer.BlockPlacerTask$1.run(BlockPlacerTask.java:75)
[23:25:52 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[23:25:52 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[23:25:52 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:641)
[23:25:52 WARN]:        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
[23:25:52 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
[23:25:52 WARN]:        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
[23:25:52 WARN]:        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
````

**Comment by confuser** [comment]
Spigot changed the packet constructor multiple times during 1.7
