### ISSUE TITLE
[AsyncWorldEdit] Task #18236 for AsyncWorldEdit v1.2 generated an exception

### ISSUE THREAD

**Issue by DjyB** [confuser/BarAPI#67]
java.lang.NullPointerException
	at me.confuser.barapi.nms.v1_6.getSpawnPacket(v1_6.java:34)
	at me.confuser.barapi.BarAPI.addDragon(BarAPI.java:452)
	at me.confuser.barapi.BarAPI.getDragon(BarAPI.java:446)
	at me.confuser.barapi.BarAPI.setMessage(BarAPI.java:252)
	at org.primesoft.asyncworldedit.BarAPIntegrator.setMessage(BarAPIntegrator.java:82)
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.setBar(BlockPlacer.java:912)
	at org.primesoft.asyncworldedit.blockPlacer.BlockPlacer.run(BlockPlacer.java:313)
	at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java:58)
	at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:822)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:777)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659)
	at net.minecraft.server.ThreadMinecraftServer.run(ThreadMinecraftServer.java:16)

**Comment by confuser** [comment]
I presume you're on Bukkit v1.6?

**Comment by DjyB** [comment]
Oui, je suis en version MCPC+1.6.4-R2.1

**Comment by DjyB** [comment]
Up
